### ISSUE TITLE
Infografía RA, RV, RM

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-FedericoVictorianoSierra#1]
[INFOGRAFÍA (FEDERICO VICTORIANO SIERRA).pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-FedericoVictorianoSierra/files/14185256/INFOGRAFIA.FEDERICO.VICTORIANO.SIERRA.pdf)

**Comment by Gregorio012** [comment]
Muy bien 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
